---
- name: Playbook to execute ping role
  hosts: rhel-db-servers
  roles:
      #- pre-setup-asm
      #- grid-install-asm
      #- db-install-asm
      #- db-creation-asm
      #- patching-asm
      #- pre-setup-obs
      #- db-install-obs
      #- db-creation-obs
      #- patching-obs