---
# tasks file for pre-setup
- name: Ping hosts
  ping:


- name: Create a new group if it doesn't exist
  shell: "/usr/sbin/groupadd -g {{ item }}"
  with_items:
    - 501 oinstall
    - 502 dba
  register: group_out  
  become: yes
  args:
    creates: /etc/group

- name: Create a new user if it doesn't exist
  shell: "/usr/sbin/useradd -u {{item}}"
  with_items:
    - 501 -g oinstall -G dba oracle
  register: user_out  
  become: yes  
  ignore_errors: yes

- name: Create the Oracle Inventory Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oraInventory
    - chown -R oracle:oinstall /u01/app/oraInventory
    - chmod -R 775 /u01/app/oraInventory
  register: user_perm  
  become: yes


- name: Creating the Oracle Grid Infrastructure Base and  Home Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/19.3.0/db
    - mkdir -p /u01/app/19.3.0/grid
    - chown -R oracle:oinstall /u01/app/19.3.0/db
    - chown -R oracle:oinstall /u01/app/
    - chmod -R 775 /u01/app/19.3.0/grid 
  register: oracle_info
  become: yes

- name: Creating Oracle Software directory
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oracle/software
    - chown -R oracle:oinstall /u01/app/oracle/software
  register: oracle_soft
  become: yes  

- name: Set SELINUX to disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  register: sel_data  
  become: yes    

- name: Reboot the machine
  block:
    - name: Reboot the system
      shell: sleep 5 && init 6
      async: 1 
      poll: 0 

    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 60
        timeout: 300
  become: yes
  when: sel_data.changed == true    

- name: Ping hosts
  ping:  